services:
  health-care-postgres:
    image: postgres:latest
    container_name: health-care-postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - n4k2-heath-care-system-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}
      interval: 10s
      retries: 5
      start_period: 30s

  health-care-system:
    build: .
    container_name: health-care-system
    restart: unless-stopped
    depends_on:
      health-care-postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  n4k2-heath-care-system-data:
